name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Kolkata"
        
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
      continue-on-error: true

    - name: Report
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: always()
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       branch: gh-pages
       folder: ./allure-results
       
    - name: Reports
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: always()
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       branch: report
       folder: ./ExtentReports
       
       
